/*
 * Es una ventana de menú que se mostrará al usuario para que pueda elegir entre dos opciones
 * de consulta que son: Consultar Cliente y Consultar Pedido
 */
package vistas;

import controladores.ControladorMenuConsultar;
import java.applet.AudioClip;
import java.sql.SQLException;

/**
 *
 * @author Inzunza Kevin
 * @author De La Cruz Joel
 * @author Pacheco Cesar
 * @version 23-04-2021
 */
public class MenuConsultarPanel extends javax.swing.JPanel {
     private final ControladorMenuConsultar cMConsultar;

    /**
     * Constuctor para iniciar el panel de menú consultar , el cual recibe el
     * sonido para los botones, el sonido para regresar y le ventana del menú
     * principal, componentes necesarios para utilizar el controlador.
     * @param sonidoBoton
     * @param regresar
     * @param principal
     * @throws java.sql.SQLException
     */
    public MenuConsultarPanel(AudioClip sonidoBoton, AudioClip regresar,PrincipalFrame principal) throws SQLException {
        initComponents();
        cMConsultar = new ControladorMenuConsultar(this,sonidoBoton,regresar,principal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        derechaJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textoCPedidos = new javax.swing.JLabel();
        registroClienteTitulo = new javax.swing.JPanel();
        manejoOTexto = new javax.swing.JLabel();
        regresarImagen = new javax.swing.JLabel();
        izquierdaJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoCClientes = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 51));
        setPreferredSize(new java.awt.Dimension(1045, 490));

        derechaJPanel.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaP.png"))); // NOI18N

        textoCPedidos.setFont(new java.awt.Font("Gayathri Thin", 1, 12)); // NOI18N
        textoCPedidos.setForeground(new java.awt.Color(204, 255, 255));
        textoCPedidos.setText("Consultar Pedidos");

        javax.swing.GroupLayout derechaJPanelLayout = new javax.swing.GroupLayout(derechaJPanel);
        derechaJPanel.setLayout(derechaJPanelLayout);
        derechaJPanelLayout.setHorizontalGroup(
            derechaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(derechaJPanelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel3)
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, derechaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoCPedidos)
                .addGap(112, 112, 112))
        );
        derechaJPanelLayout.setVerticalGroup(
            derechaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(derechaJPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addComponent(textoCPedidos)
                .addGap(54, 54, 54))
        );

        registroClienteTitulo.setBackground(new java.awt.Color(0, 153, 153));

        manejoOTexto.setFont(new java.awt.Font("EB Garamond 08", 1, 24)); // NOI18N
        manejoOTexto.setForeground(new java.awt.Color(153, 255, 204));
        manejoOTexto.setText("CONSULTAS");

        javax.swing.GroupLayout registroClienteTituloLayout = new javax.swing.GroupLayout(registroClienteTitulo);
        registroClienteTitulo.setLayout(registroClienteTituloLayout);
        registroClienteTituloLayout.setHorizontalGroup(
            registroClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroClienteTituloLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(manejoOTexto)
                .addGap(117, 117, 117))
        );
        registroClienteTituloLayout.setVerticalGroup(
            registroClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroClienteTituloLayout.createSequentialGroup()
                .addComponent(manejoOTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        regresarImagen.setBackground(new java.awt.Color(0, 153, 204));
        regresarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N

        izquierdaJPanel.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N

        textoCClientes.setFont(new java.awt.Font("Gayathri Thin", 1, 12)); // NOI18N
        textoCClientes.setForeground(new java.awt.Color(204, 255, 255));
        textoCClientes.setText("Consultar Clientes");

        javax.swing.GroupLayout izquierdaJPanelLayout = new javax.swing.GroupLayout(izquierdaJPanel);
        izquierdaJPanel.setLayout(izquierdaJPanelLayout);
        izquierdaJPanelLayout.setHorizontalGroup(
            izquierdaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izquierdaJPanelLayout.createSequentialGroup()
                .addGroup(izquierdaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(izquierdaJPanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(izquierdaJPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(textoCClientes)))
                .addGap(123, 123, 123))
        );
        izquierdaJPanelLayout.setVerticalGroup(
            izquierdaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izquierdaJPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(textoCClientes)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(registroClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281)
                .addComponent(regresarImagen)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(izquierdaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(derechaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(registroClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(regresarImagen)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(derechaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(izquierdaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel derechaJPanel;
    public javax.swing.JPanel izquierdaJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel manejoOTexto;
    private javax.swing.JPanel registroClienteTitulo;
    public javax.swing.JLabel regresarImagen;
    private javax.swing.JLabel textoCClientes;
    private javax.swing.JLabel textoCPedidos;
    // End of variables declaration//GEN-END:variables
}
