/**
 * Ventana para mostrar al usuario una interacción visual, aunque solo
 * muestra, ya que para esto contiene su controlador.
 * */
package vistas;

import controladores.ControladorRegistrarPedido;
import java.applet.AudioClip;
import javax.swing.JPanel;

/**
 * @author kevin
 * @version 16-04-2021
 */
public class RegistrarPedidoPanel extends javax.swing.JPanel {

    private final ControladorRegistrarPedido cPedido; //Atributo para utilizar el controlador

    /**
     *
     * Constuctor para iniciar el panel de registrar pedido, el cual recibe el
     * sonido para los botones, el sonido para regresar y le ventana del menú
     * principal, componentes necesarios para utilizar el controlador.
     *
     * @param sonidoBoton
     * @param regresar
     * @param mPrincipal
     */
    public RegistrarPedidoPanel(AudioClip sonidoBoton, AudioClip regresar, JPanel mPrincipal) {
        initComponents();
        cPedido = new ControladorRegistrarPedido(this, sonidoBoton, regresar, mPrincipal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroClienteTitulo = new javax.swing.JPanel();
        manejoOTexto = new javax.swing.JLabel();
        regresarImagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pedidoTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        paq1 = new javax.swing.JCheckBox();
        cantPaq1 = new javax.swing.JSpinner();
        paq2 = new javax.swing.JCheckBox();
        cantPaq2 = new javax.swing.JSpinner();
        paq3 = new javax.swing.JCheckBox();
        cantPaq3 = new javax.swing.JSpinner();
        paq4 = new javax.swing.JCheckBox();
        cantPaq4 = new javax.swing.JSpinner();
        paq5 = new javax.swing.JCheckBox();
        cantPaq5 = new javax.swing.JSpinner();
        paq6 = new javax.swing.JCheckBox();
        cantPaq6 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        extra2 = new javax.swing.JCheckBox();
        cantExt2 = new javax.swing.JSpinner();
        extra3 = new javax.swing.JCheckBox();
        cantExt3 = new javax.swing.JSpinner();
        extra4 = new javax.swing.JCheckBox();
        cantExt4 = new javax.swing.JSpinner();
        extra5 = new javax.swing.JCheckBox();
        cantExt5 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        cantExt1 = new javax.swing.JSpinner();
        extra1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numTelefono = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        pedidoTitulo2 = new javax.swing.JLabel();
        buscarBoton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pedidoTitulo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        totalPagar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totalCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pagarBoton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 51));
        setForeground(new java.awt.Color(255, 255, 0));
        setPreferredSize(new java.awt.Dimension(1045, 490));

        registroClienteTitulo.setBackground(new java.awt.Color(0, 153, 153));

        manejoOTexto.setFont(new java.awt.Font("EB Garamond 08", 1, 24)); // NOI18N
        manejoOTexto.setForeground(new java.awt.Color(153, 255, 204));
        manejoOTexto.setText("REGISTRAR PEDIDO");

        javax.swing.GroupLayout registroClienteTituloLayout = new javax.swing.GroupLayout(registroClienteTitulo);
        registroClienteTitulo.setLayout(registroClienteTituloLayout);
        registroClienteTituloLayout.setHorizontalGroup(
            registroClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroClienteTituloLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(manejoOTexto)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        registroClienteTituloLayout.setVerticalGroup(
            registroClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manejoOTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        regresarImagen.setBackground(new java.awt.Color(0, 153, 204));
        regresarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        pedidoTitulo.setFont(new java.awt.Font("Comfortaa Light", 1, 18)); // NOI18N
        pedidoTitulo.setForeground(new java.awt.Color(153, 255, 153));
        pedidoTitulo.setText("     Pedido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(pedidoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedidoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        paq1.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        paq1.setForeground(new java.awt.Color(153, 255, 153));
        paq1.setText("Paquete 1");

        cantPaq1.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantPaq1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantPaq1.setPreferredSize(new java.awt.Dimension(85, 24));

        paq2.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        paq2.setForeground(new java.awt.Color(153, 255, 153));
        paq2.setText("Paquete 2");

        cantPaq2.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantPaq2.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantPaq2.setPreferredSize(new java.awt.Dimension(85, 24));

        paq3.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        paq3.setForeground(new java.awt.Color(153, 255, 153));
        paq3.setText("Paquete 3");

        cantPaq3.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantPaq3.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantPaq3.setPreferredSize(new java.awt.Dimension(85, 24));

        paq4.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        paq4.setForeground(new java.awt.Color(153, 255, 153));
        paq4.setText("Paquete 4");

        cantPaq4.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantPaq4.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantPaq4.setPreferredSize(new java.awt.Dimension(85, 24));

        paq5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        paq5.setForeground(new java.awt.Color(153, 255, 153));
        paq5.setText("Paquete 5");

        cantPaq5.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantPaq5.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantPaq5.setPreferredSize(new java.awt.Dimension(85, 24));

        paq6.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        paq6.setForeground(new java.awt.Color(153, 255, 153));
        paq6.setText("Paquete 6");

        cantPaq6.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantPaq6.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantPaq6.setPreferredSize(new java.awt.Dimension(85, 24));

        jLabel1.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Paquete:");

        extra2.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        extra2.setForeground(new java.awt.Color(153, 255, 153));
        extra2.setText("Ensalada");

        cantExt2.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantExt2.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantExt2.setPreferredSize(new java.awt.Dimension(85, 24));

        extra3.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        extra3.setForeground(new java.awt.Color(153, 255, 153));
        extra3.setText("Tortillas de Maiz");

        cantExt3.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantExt3.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantExt3.setPreferredSize(new java.awt.Dimension(85, 24));

        extra4.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        extra4.setForeground(new java.awt.Color(153, 255, 153));
        extra4.setText("Tortillas de Harina");

        cantExt4.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantExt4.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantExt4.setPreferredSize(new java.awt.Dimension(85, 24));

        extra5.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        extra5.setForeground(new java.awt.Color(153, 255, 153));
        extra5.setText("Puré de Papa");

        cantExt5.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantExt5.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantExt5.setPreferredSize(new java.awt.Dimension(85, 24));

        jLabel2.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Extra:");

        cantExt1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        extra1.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        extra1.setForeground(new java.awt.Color(153, 255, 153));
        extra1.setText("Salsa Y Cebolla");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paq2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paq3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paq4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paq5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paq6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extra4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extra3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paq1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extra5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extra1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cantPaq5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cantPaq4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cantPaq3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cantPaq6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantExt2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantExt4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantExt5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantExt3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cantPaq1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cantPaq2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cantExt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(paq1)
                            .addComponent(cantPaq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantPaq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(paq2)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantPaq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paq3))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paq4)
                            .addComponent(cantPaq4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paq5)
                            .addComponent(cantPaq5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantPaq6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paq6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantExt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(extra1))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantExt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(extra2)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extra3)
                            .addComponent(cantExt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extra4)
                            .addComponent(cantExt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extra5)
                            .addComponent(cantExt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(406, 412));

        jLabel3.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Numero de Telefono");

        jLabel4.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("Apellido:");

        jLabel6.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Direccion:");

        numTelefono.setBackground(new java.awt.Color(153, 255, 204));
        numTelefono.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N

        nombre.setEditable(false);
        nombre.setBackground(new java.awt.Color(153, 255, 204));

        apellido.setEditable(false);
        apellido.setBackground(new java.awt.Color(153, 255, 204));
        apellido.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N

        direccion.setEditable(false);
        direccion.setBackground(new java.awt.Color(153, 255, 204));

        pedidoTitulo2.setFont(new java.awt.Font("Comfortaa Light", 1, 16)); // NOI18N
        pedidoTitulo2.setForeground(new java.awt.Color(153, 255, 153));
        pedidoTitulo2.setText("Informacion:");

        buscarBoton.setBackground(new java.awt.Color(0, 51, 51));
        buscarBoton.setFont(new java.awt.Font("Gayathri", 1, 8)); // NOI18N
        buscarBoton.setForeground(new java.awt.Color(153, 255, 204));
        buscarBoton.setText("Buscar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(numTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(pedidoTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBoton))
                .addGap(25, 25, 25)
                .addComponent(pedidoTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(direccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        pedidoTitulo1.setFont(new java.awt.Font("Comfortaa Light", 1, 18)); // NOI18N
        pedidoTitulo1.setForeground(new java.awt.Color(153, 255, 153));
        pedidoTitulo1.setText("     Cliente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(pedidoTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedidoTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel7.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("Total a Pagar    $");

        totalPagar.setEditable(false);
        totalPagar.setBackground(new java.awt.Color(153, 255, 204));
        totalPagar.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        totalPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalPagar.setPreferredSize(new java.awt.Dimension(12, 24));

        jLabel8.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 153));
        jLabel8.setText("Precio");

        totalCliente.setBackground(new java.awt.Color(153, 255, 204));
        totalCliente.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        totalCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalCliente.setPreferredSize(new java.awt.Dimension(12, 24));

        jLabel9.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 153));
        jLabel9.setText("Efectivo");

        pagarBoton.setBackground(new java.awt.Color(0, 51, 51));
        pagarBoton.setFont(new java.awt.Font("Gayathri", 1, 8)); // NOI18N
        pagarBoton.setForeground(new java.awt.Color(153, 255, 204));
        pagarBoton.setText("Pagar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(totalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pagarBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(61, 61, 61)
                .addComponent(jLabel9)
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(pagarBoton))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registroClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221)
                .addComponent(regresarImagen)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registroClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresarImagen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField apellido;
    public javax.swing.JButton buscarBoton;
    public javax.swing.JSpinner cantExt1;
    public javax.swing.JSpinner cantExt2;
    public javax.swing.JSpinner cantExt3;
    public javax.swing.JSpinner cantExt4;
    public javax.swing.JSpinner cantExt5;
    public javax.swing.JSpinner cantPaq1;
    public javax.swing.JSpinner cantPaq2;
    public javax.swing.JSpinner cantPaq3;
    public javax.swing.JSpinner cantPaq4;
    public javax.swing.JSpinner cantPaq5;
    public javax.swing.JSpinner cantPaq6;
    public javax.swing.JTextField direccion;
    public javax.swing.JCheckBox extra1;
    public javax.swing.JCheckBox extra2;
    public javax.swing.JCheckBox extra3;
    public javax.swing.JCheckBox extra4;
    public javax.swing.JCheckBox extra5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel manejoOTexto;
    public javax.swing.JTextField nombre;
    public javax.swing.JTextField numTelefono;
    public javax.swing.JButton pagarBoton;
    public javax.swing.JCheckBox paq1;
    public javax.swing.JCheckBox paq2;
    public javax.swing.JCheckBox paq3;
    public javax.swing.JCheckBox paq4;
    public javax.swing.JCheckBox paq5;
    public javax.swing.JCheckBox paq6;
    private javax.swing.JLabel pedidoTitulo;
    private javax.swing.JLabel pedidoTitulo1;
    private javax.swing.JLabel pedidoTitulo2;
    private javax.swing.JPanel registroClienteTitulo;
    public javax.swing.JLabel regresarImagen;
    public javax.swing.JTextField totalCliente;
    public javax.swing.JTextField totalPagar;
    // End of variables declaration//GEN-END:variables
}
