/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.applet.AudioClip;
import java.awt.Color;
import static java.lang.Math.abs;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kevin
 */
public class RegistrarPedidoPanel extends javax.swing.JPanel {

    private final JPanel mPrincipal;
    private final AudioClip sonidoBoton;
    private final AudioClip regresar;
    private final AudioClip sonidoDePago;
    /**
     * Creates new form RegistrarPedidoFrame
     *
     * @param sonidoBoton
     * @param regresar
     * @param mPrincipal
     */
    public RegistrarPedidoPanel(AudioClip sonidoBoton, AudioClip regresar, JPanel mPrincipal) {
        initComponents();
        sonidoDePago=java.applet.Applet.newAudioClip(getClass().getResource("../sonidos/pago-realizado.wav"));
        this.sonidoBoton = sonidoBoton;
        this.mPrincipal = mPrincipal;
        this.regresar = regresar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroClienteTitulo = new javax.swing.JPanel();
        manejoOTexto = new javax.swing.JLabel();
        regresarImagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pedidoTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        paq1 = new javax.swing.JCheckBox();
        cantPaq1 = new javax.swing.JSpinner();
        paq2 = new javax.swing.JCheckBox();
        cantPaq2 = new javax.swing.JSpinner();
        paq3 = new javax.swing.JCheckBox();
        cantPaq3 = new javax.swing.JSpinner();
        paq4 = new javax.swing.JCheckBox();
        cantPaq4 = new javax.swing.JSpinner();
        paq5 = new javax.swing.JCheckBox();
        cantPaq5 = new javax.swing.JSpinner();
        paq6 = new javax.swing.JCheckBox();
        cantPaq6 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        extra1 = new javax.swing.JCheckBox();
        cantExt1 = new javax.swing.JSpinner();
        extra2 = new javax.swing.JCheckBox();
        cantExt2 = new javax.swing.JSpinner();
        extra3 = new javax.swing.JCheckBox();
        cantExt3 = new javax.swing.JSpinner();
        extra4 = new javax.swing.JCheckBox();
        cantExt4 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numTelefono = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        pedidoTitulo2 = new javax.swing.JLabel();
        buscarBoton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pedidoTitulo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        totalPagar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totalCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pagarBoton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 51));
        setForeground(new java.awt.Color(255, 255, 0));
        setPreferredSize(new java.awt.Dimension(1045, 490));

        registroClienteTitulo.setBackground(new java.awt.Color(0, 153, 153));

        manejoOTexto.setFont(new java.awt.Font("EB Garamond 08", 1, 24)); // NOI18N
        manejoOTexto.setForeground(new java.awt.Color(153, 255, 204));
        manejoOTexto.setText("REGISTRAR PEDIDO");

        javax.swing.GroupLayout registroClienteTituloLayout = new javax.swing.GroupLayout(registroClienteTitulo);
        registroClienteTitulo.setLayout(registroClienteTituloLayout);
        registroClienteTituloLayout.setHorizontalGroup(
            registroClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroClienteTituloLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(manejoOTexto)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        registroClienteTituloLayout.setVerticalGroup(
            registroClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manejoOTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        regresarImagen.setBackground(new java.awt.Color(0, 153, 204));
        regresarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N
        regresarImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarImagenMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        pedidoTitulo.setFont(new java.awt.Font("Comfortaa Light", 1, 18)); // NOI18N
        pedidoTitulo.setForeground(new java.awt.Color(153, 255, 153));
        pedidoTitulo.setText("     Pedido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(pedidoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedidoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        paq1.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        paq1.setForeground(new java.awt.Color(153, 255, 153));
        paq1.setText("Paquete 1");
        paq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paq1ActionPerformed(evt);
            }
        });

        cantPaq1.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantPaq1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantPaq1.setPreferredSize(new java.awt.Dimension(85, 24));

        paq2.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        paq2.setForeground(new java.awt.Color(153, 255, 153));
        paq2.setText("Paquete 2");
        paq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paq2ActionPerformed(evt);
            }
        });

        cantPaq2.setFont(new java.awt.Font("Comfortaa Light", 0, 12)); // NOI18N
        cantPaq2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantPaq2.setPreferredSize(new java.awt.Dimension(85, 24));

        paq3.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        paq3.setForeground(new java.awt.Color(153, 255, 153));
        paq3.setText("Paquete 3");
        paq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paq3ActionPerformed(evt);
            }
        });

        cantPaq3.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantPaq3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantPaq3.setPreferredSize(new java.awt.Dimension(85, 24));

        paq4.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        paq4.setForeground(new java.awt.Color(153, 255, 153));
        paq4.setText("Paquete 4");
        paq4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paq4ActionPerformed(evt);
            }
        });

        cantPaq4.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantPaq4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantPaq4.setPreferredSize(new java.awt.Dimension(85, 24));

        paq5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        paq5.setForeground(new java.awt.Color(153, 255, 153));
        paq5.setText("Paquete 5");
        paq5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paq5ActionPerformed(evt);
            }
        });

        cantPaq5.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantPaq5.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantPaq5.setPreferredSize(new java.awt.Dimension(85, 24));

        paq6.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        paq6.setForeground(new java.awt.Color(153, 255, 153));
        paq6.setText("Paquete 6");
        paq6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paq6ActionPerformed(evt);
            }
        });

        cantPaq6.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantPaq6.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantPaq6.setPreferredSize(new java.awt.Dimension(85, 24));

        jLabel1.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Paquete:");

        extra1.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        extra1.setForeground(new java.awt.Color(153, 255, 153));
        extra1.setText("Ensalada");
        extra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extra1ActionPerformed(evt);
            }
        });

        cantExt1.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantExt1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantExt1.setPreferredSize(new java.awt.Dimension(85, 24));

        extra2.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        extra2.setForeground(new java.awt.Color(153, 255, 153));
        extra2.setText("Tortillas de Maiz");
        extra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extra2ActionPerformed(evt);
            }
        });

        cantExt2.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantExt2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantExt2.setPreferredSize(new java.awt.Dimension(85, 24));

        extra3.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        extra3.setForeground(new java.awt.Color(153, 255, 153));
        extra3.setText("Tortillas de Harina");
        extra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extra3ActionPerformed(evt);
            }
        });

        cantExt3.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantExt3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantExt3.setPreferredSize(new java.awt.Dimension(85, 24));

        extra4.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        extra4.setForeground(new java.awt.Color(153, 255, 153));
        extra4.setText("Orden de Papas");
        extra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extra4ActionPerformed(evt);
            }
        });

        cantExt4.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        cantExt4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantExt4.setPreferredSize(new java.awt.Dimension(85, 24));

        jLabel2.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Extra:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(paq2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paq3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paq4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paq5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paq6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paq1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(extra1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extra3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extra4)
                    .addComponent(extra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cantPaq5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantPaq4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantPaq3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cantPaq6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cantExt1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cantPaq2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cantExt3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cantExt4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cantExt2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cantPaq1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paq1)
                            .addComponent(cantPaq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paq2)
                            .addComponent(cantPaq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantPaq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paq3))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paq4)
                            .addComponent(cantPaq4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paq5)
                            .addComponent(cantPaq5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantPaq6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paq6))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantExt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(extra1)
                                    .addComponent(jLabel2))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(extra2)
                                    .addComponent(cantExt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(extra3)
                                    .addComponent(cantExt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(extra4)
                                    .addComponent(cantExt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10))))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(406, 412));

        jLabel3.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Numero de Telefono");

        jLabel4.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("Apellido:");

        jLabel6.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Direccion:");

        numTelefono.setBackground(new java.awt.Color(153, 255, 204));
        numTelefono.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N

        nombre.setEditable(false);
        nombre.setBackground(new java.awt.Color(153, 255, 204));

        apellido.setEditable(false);
        apellido.setBackground(new java.awt.Color(153, 255, 204));
        apellido.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N

        direccion.setEditable(false);
        direccion.setBackground(new java.awt.Color(153, 255, 204));

        pedidoTitulo2.setFont(new java.awt.Font("Comfortaa Light", 1, 16)); // NOI18N
        pedidoTitulo2.setForeground(new java.awt.Color(153, 255, 153));
        pedidoTitulo2.setText("Informacion:");

        buscarBoton.setBackground(new java.awt.Color(0, 51, 51));
        buscarBoton.setFont(new java.awt.Font("Gayathri", 1, 8)); // NOI18N
        buscarBoton.setForeground(new java.awt.Color(153, 255, 204));
        buscarBoton.setText("Buscar");
        buscarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarBotonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarBotonMouseEntered(evt);
            }
        });
        buscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(numTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(pedidoTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBoton))
                .addGap(25, 25, 25)
                .addComponent(pedidoTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(direccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        pedidoTitulo1.setFont(new java.awt.Font("Comfortaa Light", 1, 18)); // NOI18N
        pedidoTitulo1.setForeground(new java.awt.Color(153, 255, 153));
        pedidoTitulo1.setText("     Cliente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(pedidoTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedidoTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel7.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("Total a Pagar");

        totalPagar.setBackground(new java.awt.Color(153, 255, 204));
        totalPagar.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        totalPagar.setPreferredSize(new java.awt.Dimension(12, 24));

        jLabel8.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 153));
        jLabel8.setText("Precio");

        totalCliente.setBackground(new java.awt.Color(153, 255, 204));
        totalCliente.setFont(new java.awt.Font("Comfortaa Light", 0, 14)); // NOI18N
        totalCliente.setPreferredSize(new java.awt.Dimension(12, 24));

        jLabel9.setFont(new java.awt.Font("Comfortaa Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 153));
        jLabel9.setText("Efectivo");

        pagarBoton.setBackground(new java.awt.Color(0, 51, 51));
        pagarBoton.setFont(new java.awt.Font("Gayathri", 1, 8)); // NOI18N
        pagarBoton.setForeground(new java.awt.Color(153, 255, 204));
        pagarBoton.setText("Pagar");
        pagarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pagarBotonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pagarBotonMouseEntered(evt);
            }
        });
        pagarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(34, 34, 34)
                .addComponent(totalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pagarBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(48, 48, 48)
                .addComponent(jLabel9)
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(pagarBoton))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registroClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233)
                .addComponent(regresarImagen)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registroClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresarImagen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regresarImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarImagenMouseClicked
        Icon icono = new ImageIcon(getClass().getResource("../imagenes/regreso.png"));
        regresar.play();
        if (JOptionPane.showConfirmDialog(null, "¿Desea regresar al menu principal?", "Regresar", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,icono) == 0) {
            this.setVisible(false);
            mPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_regresarImagenMouseClicked

    private void extra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extra4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extra4ActionPerformed

    private void extra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extra3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extra3ActionPerformed

    private void extra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extra2ActionPerformed

    private void extra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extra1ActionPerformed

    private void paq6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paq6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paq6ActionPerformed

    private void paq5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paq5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paq5ActionPerformed

    private void paq4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paq4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paq4ActionPerformed

    private void paq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paq3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paq3ActionPerformed

    private void paq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paq2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paq2ActionPerformed

    private void paq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paq1ActionPerformed

    private void buscarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBotonMouseExited
        buscarBoton.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_buscarBotonMouseExited

    private void buscarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBotonMouseEntered
        buscarBoton.setBackground(new Color(0, 102, 102));
        sonidoBoton.play();
    }//GEN-LAST:event_buscarBotonMouseEntered

    private void buscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBotonActionPerformed

    }//GEN-LAST:event_buscarBotonActionPerformed

    private void pagarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagarBotonMouseExited
        pagarBoton.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_pagarBotonMouseExited

    private void pagarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagarBotonMouseEntered
        pagarBoton.setBackground(new Color(0, 102, 102));
        sonidoBoton.play();
    }//GEN-LAST:event_pagarBotonMouseEntered

    private void pagarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarBotonActionPerformed
       Icon icono = new ImageIcon(getClass().getResource("../imagenes/pagar.png"));
        if (JOptionPane.showConfirmDialog(null, "Se efectuara el pago,¿Desea confirmar?","Confirmacion", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,icono) == 0) {
        }
        if (!totalPagar.getText().isEmpty() && !totalCliente.getText().isEmpty()) {
            int total = Integer.parseInt(totalCliente.getText()) - Integer.parseInt(totalPagar.getText());

            if (total > 0) {
                sonidoDePago.play();
                total = abs(total);
                JOptionPane.showMessageDialog(null, "Gracias por su Compra!\n" + "Cambio: " + total, "Pago Exitoso", JOptionPane.INFORMATION_MESSAGE,icono);
            } else if (total == 0) {
                sonidoDePago.play();
                JOptionPane.showMessageDialog(null, "Gracias por su Compra!", "Pago Exitoso", JOptionPane.INFORMATION_MESSAGE,icono);
            } else {
                regresar.play();
                JOptionPane.showMessageDialog(null, "No se ha completado el monto a pagar", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Verifique que todos los campos esten ingresados", "Datos faltantes", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_pagarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JButton buscarBoton;
    private javax.swing.JSpinner cantExt1;
    private javax.swing.JSpinner cantExt2;
    private javax.swing.JSpinner cantExt3;
    private javax.swing.JSpinner cantExt4;
    private javax.swing.JSpinner cantPaq1;
    private javax.swing.JSpinner cantPaq2;
    private javax.swing.JSpinner cantPaq3;
    private javax.swing.JSpinner cantPaq4;
    private javax.swing.JSpinner cantPaq5;
    private javax.swing.JSpinner cantPaq6;
    private javax.swing.JTextField direccion;
    private javax.swing.JCheckBox extra1;
    private javax.swing.JCheckBox extra2;
    private javax.swing.JCheckBox extra3;
    private javax.swing.JCheckBox extra4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel manejoOTexto;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numTelefono;
    private javax.swing.JButton pagarBoton;
    private javax.swing.JCheckBox paq1;
    private javax.swing.JCheckBox paq2;
    private javax.swing.JCheckBox paq3;
    private javax.swing.JCheckBox paq4;
    private javax.swing.JCheckBox paq5;
    private javax.swing.JCheckBox paq6;
    private javax.swing.JLabel pedidoTitulo;
    private javax.swing.JLabel pedidoTitulo1;
    private javax.swing.JLabel pedidoTitulo2;
    private javax.swing.JPanel registroClienteTitulo;
    private javax.swing.JLabel regresarImagen;
    private javax.swing.JTextField totalCliente;
    private javax.swing.JTextField totalPagar;
    // End of variables declaration//GEN-END:variables
}
